<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/applyingmatricestask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Apply the identity matrix ***I3*** to the vector ***u***.

In [1]:
import numpy as np
import torch

In [3]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [6]:
u_pt = torch.tensor([2, 5, 3])
u_pt

tensor([2, 5, 3])

In [7]:
torch.matmul(I, u_pt)

tensor([2, 5, 3])

2. Apply the matrix ***B*** to the vector ***u***.

In [8]:
B = np.array([[2, 0, -1], [-2, 3, 1], [0, 4, -1]])
B

array([[ 2,  0, -1],
       [-2,  3,  1],
       [ 0,  4, -1]])

In [12]:
u = np.array([2, 5, 3])
u

array([2, 5, 3])

In [13]:
B_pt = torch.tensor([[2, 0, -1], [-2, 3, 1], [0, 4, -1]])
B_pt

tensor([[ 2,  0, -1],
        [-2,  3,  1],
        [ 0,  4, -1]])

In [10]:
u_pt = torch.tensor([2, 5, 3])
u_pt

tensor([2, 5, 3])

In [15]:
torch.matmul(B_pt, u_pt)

tensor([ 1, 14, 17])

3. Concatenante vector ***u*** with vector ***u2*** to form a matrix U, then apply the matrix ***B*** to the matrix ***U***.

In [21]:
U = np.array([[2, 0], [5, -4], [-3, 6]])
U

array([[ 2,  0],
       [ 5, -4],
       [-3,  6]])

In [22]:
np.dot(B, U)

array([[  7,  -6],
       [  8,  -6],
       [ 23, -22]])