<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/determinanttest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import torch

In [3]:
X = np.array([[25, 2], [3, 4]])
X

array([[25,  2],
       [ 3,  4]])

In [4]:
np.linalg.det(X)

94.0

In [9]:
X = torch.tensor([[25, 2], [3, 4.]])

In [10]:
torch.det(X)

tensor(94.)

In [5]:
Y = np.array([[-2, 0], [0, -2]])
Y

array([[-2,  0],
       [ 0, -2]])

In [6]:
np.linalg.det(Y)

4.0

In [12]:
Y = torch.tensor([[-2, 0], [0, -2.]])

In [13]:
torch.det(Y)

tensor(4.)

In [14]:
X = np.array([[2, 1, -3], [4, -5, 2], [0, -1, 3]])
X

array([[ 2,  1, -3],
       [ 4, -5,  2],
       [ 0, -1,  3]])

In [15]:
np.linalg.det(X)

-26.000000000000014

In [16]:
X = torch.tensor([[2, 1, -3], [4, -5, 2], [0, -1, 3.]])

In [17]:
torch.det(X)

tensor(-26.)