<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/eigendecompositionexercices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Use PyTorch to decompose the matrix $P$ (below) into its components $V$, $\Lambda$, and $V^{-1}$. Confirm that $P = V \Lambda V^{-1}$.

In [2]:
import numpy as np

In [3]:
import torch

In [4]:
P = torch.tensor ([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [5]:
lambdas, V_P = torch.linalg.eig(P)

In [6]:
lambdas

tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])

In [7]:
V_P

tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
        [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
        [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]])

In [8]:
V_Pinv = torch.linalg.inv(V_P)
V_Pinv

tensor([[ 1.1356+0.j,  0.0102+0.j, -0.2868+0.j],
        [ 0.3914+0.j, -0.7198-0.j, -1.0032-0.j],
        [ 0.0817+0.j, -1.1164-0.j,  0.2052+0.j]])

In [9]:
Lambda = torch.diag(lambdas)
Lambda

tensor([[23.7644+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  6.6684+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -3.4328+0.j]])

In [10]:
np.dot(P, np.dot(Lambda, V_Pinv))

array([[ 681.3009   +0.j,  -22.678679 +0.j, -180.23001  +0.j],
       [  75.46045  +0.j,   14.162617 +0.j,   -7.7693653+0.j],
       [ 152.08485  +0.j,  -17.053043 +0.j,  -83.72035  +0.j]],
      dtype=complex64)

2. Use PyTorch to decompose the symmetric matrix $S$ (below) into its components $Q$, $\Lambda$, and $Q^T$. Confirm that $S = Q \Lambda Q^T$.

In [11]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [16]:
lambdas, V_S = torch.linalg.eig(S)

In [13]:
lambdas

array([26.236076 ,  3.2434747, -2.479551 ], dtype=float32)

In [17]:
Lambda = torch.diag(lambdas)
Lambda

tensor([[26.2361+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  3.2435+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -2.4796+0.j]])

In [18]:
V_S

tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
        [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
        [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]])

In [19]:
np.dot(V_S, np.dot(Lambda, V_S.T))

array([[24.999992 +0.j,  1.9999996+0.j, -4.999998 +0.j],
       [ 1.9999996+0.j, -2.0000002+0.j,  0.9999999+0.j],
       [-4.9999986+0.j,  0.9999999+0.j,  3.9999995+0.j]], dtype=complex64)