<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/Eigenvectors_in_%3E2_Dimensionsexcercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Use PyTorch to confirm $Xv = \lambda v$ for the first eigenvector of $X$.

In [1]:
import numpy as np

In [2]:
X = np.array([[25, 2, 9], [5, 26, -5], [3, 7, -1]])
X

array([[25,  2,  9],
       [ 5, 26, -5],
       [ 3,  7, -1]])

In [3]:
lambdas_X, V_X = np.linalg.eig(X)

In [4]:
V_X

array([[-0.71175736, -0.6501921 , -0.34220476],
       [-0.66652125,  0.74464056,  0.23789717],
       [-0.22170001,  0.15086635,  0.90901091]])

In [5]:
lambdas_X

array([29.67623202, 20.62117365, -0.29740567])

Confirm $Xv = \lambda v$ for an example eigenvector:

In [7]:
v_X = V_X[:,1]
v_X

array([-0.6501921 ,  0.74464056,  0.15086635])

In [8]:
lambda_X = lambdas_X[1]
lambda_X

20.62117365053535

In [9]:
np.dot(X, v_X)

array([-13.40772428,  15.3553624 ,   3.11104129])

In [10]:
lambda_X * v_X

array([-13.40772428,  15.3553624 ,   3.11104129])

2. Confirm $Xv = \lambda v$ for the remaining eigenvectors of $X$ (you can use NumPy or PyTorch, whichever you prefer).

In [12]:
v_X = V_X[:,2]
v_X

array([-0.34220476,  0.23789717,  0.90901091])

In [13]:
lambda_X = lambdas_X[2]
lambda_X

-0.29740567448426547

In [14]:
np.dot(X, v_X)

array([ 0.10177364, -0.07075197, -0.270345  ])

In [15]:
lambda_X * v_X

array([ 0.10177364, -0.07075197, -0.270345  ])