<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/matrixmultipicationexercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array ([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
b = np.array([-1, 1, -2])
b

array([-1,  1, -2])

In [15]:
np.dot(A, b)

array([ -3,  -9, -15])

In [6]:
import torch

In [7]:
A_pt = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
A_pt

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [16]:
b_pt = torch.tensor([-1, 1, -2])
b_pt

tensor([-1,  1, -2])

In [17]:
torch.matmul(A_pt, b_pt)

tensor([ -3,  -9, -15])

In [10]:
import tensorflow as tf

In [11]:
A_tf = tf.Variable([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [18]:
b_tf = tf.Variable([-1, 1, -2])
b_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([-1,  1, -2], dtype=int32)>

In [19]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ -3,  -9, -15], dtype=int32)>

***I***3

In [20]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [21]:
x_pt = torch.tensor([-1, 1, -2])
x_pt

tensor([-1,  1, -2])

In [22]:
torch.matmul(I, x_pt)

tensor([-1,  1, -2])

**two matrices**

In [23]:
B_pt = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
B_pt

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [25]:
A_pt = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T
A_pt

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

In [26]:
torch.matmul(B_pt, A_pt)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])