<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/segment2test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What is YT ?

In [9]:
import numpy as np

In [13]:
Y = np.array ([[42, 4, 7, 99], [-99, -3, 17, 22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [14]:
Y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

2. What is the Hadamard product of these matrices?

In [15]:
X = np.array ([[25, 10], [-2, 1]])
X

array([[25, 10],
       [-2,  1]])

In [16]:
A = np.array ([[-1, 7], [10, 8]])
A

array([[-1,  7],
       [10,  8]])

In [17]:
A * X

array([[-25,  70],
       [-20,   8]])

3. What is the dot product of the tensors ***w*** and ***x***?

In [18]:
w = np.array ([-1, 2, -2])
w

array([-1,  2, -2])

In [19]:
x = np.array ([5, 10, 0])
x

array([ 5, 10,  0])

In [20]:
np.dot (w, x)

15

In [24]:
import torch

In [27]:
w_pt = torch.tensor([-1, 2, -2])
w_pt

tensor([-1,  2, -2])

In [28]:
x_pt = torch.tensor([5, 10, 0])
x_pt

tensor([ 5, 10,  0])

In [29]:
np.dot(w_pt, x_pt)

15

In [31]:
torch.dot(torch.tensor([-1, 2, -2.]), torch.tensor([5, 10, 0.]))

tensor(15.)

In [34]:
import tensorflow as tf

In [35]:
w_tf = tf.Variable([-1, 2, -2])
w_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([-1,  2, -2], dtype=int32)>

In [36]:
x_tf = tf.Variable([5, 10, 0])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 10,  0], dtype=int32)>

In [38]:
tf.reduce_sum(tf.multiply(w_tf, x_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=15>