<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/SVDexercices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using the matrix P from the preceding PyTorch exercises, demonstrate that these three SVD-eigendecomposition equations are true.

In [2]:
import numpy as np

In [3]:
import torch

In [4]:
P = torch.tensor ([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [5]:
U, d, VT = torch.linalg.svd(P)

In [6]:
U

tensor([[-0.9757,  0.1823,  0.1214],
        [-0.0975,  0.1350, -0.9860],
        [-0.1961, -0.9739, -0.1140]])

In [7]:
VT

tensor([[-0.9810, -0.1196,  0.1528],
        [ 0.0113, -0.8211, -0.5706],
        [-0.1937,  0.5581, -0.8069]])

In [8]:
d

tensor([26.1632,  8.1875,  2.5395])

In [19]:
torch.diag(d)

tensor([[26.1632,  0.0000,  0.0000],
        [ 0.0000,  8.1875,  0.0000],
        [ 0.0000,  0.0000,  2.5395]])

In [20]:
p_pT = torch.linalg.matmul(P,P.T)

In [21]:
lambdas, eign_p_pT = torch.linalg.eig(torch.linalg.matmul(P,P.T))

In [22]:
pT_p = torch.linalg.matmul(P.T,P)

In [23]:
lambdas, eign_pT_p = torch.linalg.eig(torch.linalg.matmul(P.T,P))

In [25]:
P_repeated = torch.linalg.matmul(U, (torch.linalg.matmul(torch.diag(d),VT)))
P_repeated

tensor([[25.0000,  2.0000, -5.0000],
        [ 3.0000, -2.0000,  1.0000],
        [ 5.0000,  7.0000,  4.0000]])