<a href="https://colab.research.google.com/github/sassymag/machinelearning/blob/main/The_Moore_Penrose_PseudoinverseExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import tensorflow as tf

In [3]:
A_p = torch.tensor([[-1, 2], [3, -2], [5, 7.]])
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [4]:
U_p, d_p, VT_p = torch.linalg.svd(A_p)

In [5]:
U_p

tensor([[ 0.1271,  0.4741,  0.8713],
        [ 0.0016, -0.8785,  0.4778],
        [ 0.9919, -0.0593, -0.1124]])

In [6]:
d_p

tensor([8.6692, 4.1043])

In [7]:
VT_p

tensor([[ 0.5580,  0.8298],
        [-0.8298,  0.5580]])

In [8]:
D = torch.diag(d_p)
D

tensor([[8.6692, 0.0000],
        [0.0000, 4.1043]])

In [9]:
1/8.669

0.11535355865728457

In [10]:
1/4.104

0.24366471734892786

In [11]:
Dinv = torch.linalg.inv(D)
Dinv

tensor([[0.1154, 0.0000],
        [0.0000, 0.2436]])

In [12]:
Dplus = torch.concatenate((Dinv, torch.tensor([[0, 0]]).T), 1)
Dplus

tensor([[0.1154, 0.0000, 0.0000],
        [0.0000, 0.2436, 0.0000]])

In [13]:
torch.mm(VT_p.T, torch.mm(Dplus, U_p.T))

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [14]:
torch.linalg.pinv(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])